name = "UnitOne Landings"
client_id = "d57ef78d7ee691f86fa88912ddeda263"
application_url = "https://unit-one-romania.vercel.app"
embedded = true

[access_scopes]
scopes = "write_products,read_products,read_themes,write_themes"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://unit-one-romania.vercel.app/api/auth"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.privacy_compliance]]
  customer_deletion_url = "https://unit-one-romania.vercel.app/api/webhooks"
  customer_data_request_url = "https://unit-one-romania.vercel.app/api/webhooks"
  shop_deletion_url = "https://unit-one-romania.vercel.app/api/webhooks"

[pos]
embedded = false
